-- AlterTable
ALTER TABLE `users` MODIFY `LangCd` TINYINT NOT NULL DEFAULT 0,
    MODIFY `city_id` SMALLINT NOT NULL DEFAULT 0,
    MODIFY `country_code` SMALLINT NOT NULL DEFAULT 0,
    MODIFY `Gender` TINYINT NOT NULL DEFAULT 0,
    MODIFY `Stat` TINYINT NOT NULL DEFAULT 0,
    MODIFY `Role` TINYINT NOT NULL DEFAULT 0;
